export const GET_FILMS_START = 'GET_FILMS_START';
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS';
export const GET_FILMS_ERROR = 'GET_FILMS_ERROR';

export const SEARCH_FILMS_START = 'SEARCH_FILMS_START';
export const SEARCH_FILMS_SUCCESS = 'SEARCH_FILMS_SUCCESS';

export const SET_DATA = 'SET_DATA';
